function plot_returns end
function plot_bar end
function plot_risk_contribution end
function plot_frontier_area end
function plot_drawdown end
function plot_hist end
function plot_range end
function plot_frontier end
function plot_clusters end
function plot_dendrogram end
function plot_network end
function plot_cluster_network end
